server:
  port: 9012
spring:
  application:
    name: tensquare-manager   # 模块名
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true # 跨域访问
zuul:
  routes:
    manage-friend:
      path: /friend/**
      serviceId: tensquare-friend
    manage-user:
      path: /user/**
      serviceId: tensquare-user