server:
  port: 9011
spring:
  application:
    name: tensquare-friend
  datasource:   # 配置数据源
    druid:
      url: jdbc:mysql://127.0.0.1:3306/tensquare_friend?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: hanjie
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  jpa:      # 配置jpa
    database: mysql
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true     # 跨域访问

ribbon:
  ConnectTimeout: 4000 #请求连接的超时时间，默认时间为1秒
  ReadTimeout: 4000 #请求处理的超时时间

feign:
  hystrix:
    enabled: true
